services:
  speedtest-bot:
    build: .
    container_name: ufo_speedtest_bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - speedtest-data:/data

volumes:
  speedtest-data:
